language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker pull spikeforest/codepod_spikeforest2

install:
  - pip install pytest
  - pip install codepod
  - pip install ./mountaintools
  - pip install ./spikeforest

script:
  - codepod --command='devel/codepod_test.sh' --no-pull --docker_opts="-e EXTRA_CMD='./devel/codepod_test.sh'" .
  - PYTHONDONTWRITEBYTECODE=1 python -m pytest -p no:cacheprovider
