language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: ZckOgVv1o6+JqJCe8nyJ0CAFGfcTA1oguJ2u+9gXAgcmroGim/pA7NIYmu8DZf1y4HyMao2EWLZ4Mcnl7ksz1KHlIjX7Ty4uUT2padqHQpiOLUU2VTb096sY7jUteN5qZtoyqbDn3/SGmndn1Vr9bB52xi2hylDsUjOA/5KXHJ6T/3k/NBLmEgP3NokPyF0qWj9ZmpvJuYYdl/+G2QzT+zHra0XGPlPE0J1jiTV14Qi9zKIQeUjRGdQkP9uGv+9a0jzAUSsxef3+JmuzqM0pe9BZH/ol3EKHpGt9DwdbuwlZzKvpBqKfAU7PH9kEA+QEEp+2CeodfbPF4o9p6cpq8LyNV5Eq0vWyDiIgULmBQcfnbRg4zebiGgX8qmkjXK/u1NbiAJj0jbQOOoqe9qldXgYMYu3OQfWkYzsc3cHezZdEukZ0th5YMT8Ys1m7DPT4nwMD2JTO/sDcHOSyLXHK6XZgHT2Ew556Kmd2WyfLR3rjACumGtjpz0SuqHrXm15zaTsnw/FihxlI0ok45j8SRIBaV3rL9DV8nGHYNzoEVwhXVYUlQQbuO5V7VEHNorONl8QbrbrvxVTAP4abOuOy/iQPv+Dano5EInlTniFuKAkJBNUl3a4Iq+xHaXrfprIlIfU0EMyZMManjtuVNjHxG1OtHF03bDF+EEosnBBTd2Y=
